src/Routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::prefix('/w-admin')->middleware('auth')->group( function () {
    Route::resource('pages' , 'PageController');
    Route::get('pages/{id}/subpages','PageController@subPages')->name('subpages');
    Route::post('pages/checkurl','PageController@urlControl')->name('pages.checkurl');
    Route::resource('files' , 'FileController');
    Route::post('files/ajax','FileController@ajax')->name('file.ajax');
    Route::resource('languages' , 'LanguageController');
    Route::post('languages/update/extensions' , 'LanguageController@extensions')->name('update.Extensions');
    Route::post('languages/update/default' , 'LanguageController@changeDefault')->name('change.default');
    Route::post('languages/update/list','LanguageController@updateList')->name('updateList');
    Route::get('logs','LogController@index')->name('log-index');

    //Category
    Route::resource('categories','CategoryController');
    Route::post('category/order','CategoryController@order')->name('categories.order');
    Route::post('category/getCategory','CategoryController@getCategory')->name('get-category');
    Route::post('category/updateCategory','CategoryController@customUpdate')->name('update-category');
    Route::post('category/sortCategory','CategoryController@sortCategory')->name('sort-category');

    Route::resource('metas' , 'MetaController');
    Route::resource('redirects' , 'RedirectController');

    //Form-Ebulletin
    Route::resource('forms','FormController');
    Route::resource('forms.messages','MessageController');
    Route::resource('messages','MessageController')->only(['show','store']);
    Route::resource('ebulletins' , 'EbulletinController');

    //Auth
    Route::resource('users' , 'UserController');
    Route::resource('roles' , 'RoleController');

    Route::get('/','HomeController@index')->name('panel');

    Route::get('login',function (){ return view('auth/login');})->name('login');

    Route::get('getFilePage','FileController@getFilePage')->name('files.getFilePage');
    Route::get('getFilePageDetail','FileController@getFilePageDetail')->name('files.getFilePageDetail');

    Route::post('saveFilePage','FileController@saveFilePage')->name('files.saveFilePage');
    Route::post('saveFilePageDetail','FileController@saveFilePageDetail')->name('files.saveFilePageDetail');

    Route::post('uploadFile','FileController@uploadFile')->name('files.uploadFile');

    Route::get('googleAnalytics','AnalyticsController@google')->name('analytics.google');

    Route::resource('slider','SliderController');
    Route::post('slider/add-image','SliderController@addImage')->name('addImage');
    Route::post('slider/delete-image','SliderController@deleteImage')->name('delimage');
    Route::post('slider/get-slider-image','SliderController@getSliderImage')->name('getSliderImage');
    Route::post('slider/edit-image','SliderController@editImage')->name('editImage');
    Route::post('slider/sort-image','SliderController@sortImage')->name('sortImage');
    //Menu
    Route::resource('menu', 'MenuController');
    Route::post('menu/ajax','MenuController@ajax')->name('menuajax');
    Route::post('menu/item//delete','MenuController@destroyMenuItem')->name('delete-item');
    Route::post('menuitem/ajax/','MenuController@storeMenuItem')->name('menuitemajax');
    Route::post('menuitem/edit/ajax/','MenuController@editMenuItem')->name('edit-menuitem-ajax');
    Route::post('menu/item','MenuController@getMenuItem')->name('get-menuitem');

});

Route::get('w-admin/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('w-admin/login/', 'Auth\LoginController@login');
Route::post('w-admin/logout', 'Auth\LoginController@logout')->name('logout');


Route::group(['prefix'=>'ebulletin'],function(){
    Route::get('activate/{token}', 'ActionsController@activate')->name('ebulletin.activate');
    Route::get('cancel/{token}', 'ActionsController@cancel')->name('ebulletin.cancel');
    Route::post('save','ActionsController@save')->name('ebulletin.save');
});


Route::post('form/store','MessageController@store')->name('form');
Route::fallback('UrlController@url');

Route::get('/home', 'HomeController@index')->name('home');
Route::any('/ckfinder/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')
    ->name('ckfinder_connector');

Route::any('/ckfinder/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')
    ->name('ckfinder_browser');

src/Models/Redirect.php
<?php

namespace CMS\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Redirect extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'from', 'to', 'code', 'status'
    ];
}

src/Resources/views/panel/redirect/create.blade.php
@extends('cms::panel.newinc.app')
@push('css')

@endpush

@push('js')
@endpush
@section('content')

    <div class="main-content container-fluid">
        <div class="card">
            <div class="card-header">
                <div class="card-content">
                    <div class="card-body">
                        <div class="divider">
                            <div class="divider-text">{{ trans('cms::panel.redirects.create') }}</div>
                        </div>
                        <div class="card-content">
                            <div class="card-body">
                                <form method="POST" action="{!! route('redirects.store') !!}" class="form-control-lg">
                                    @method('POST')
                                    @csrf
                                    <div class="form-group">
                                        <label>{!! trans('cms::panel.redirects.from') !!}</label>
                                        <input type="text" class="form-control shadow-sm" id="from" name="from"  value="{!! old('from') !!}">
                                        @include('cms::panel.inc.form_error',['input_name' => 'from'])
                                    </div>
                                    <div class="form-group">
                                        <label>{!! trans('cms::panel.redirects.to') !!}</label>
                                        <input type="text" class="form-control shadow-sm" id="to" name="to"  value="{!! old('to') !!}">
                                        @include('cms::panel.inc.form_error',['input_name' => 'to'])
                                    </div>
                                    <div class="form-group">
                                        <label>{!! trans('cms::panel.redirects.code') !!}</label>
                                        <input type="text" class="form-control shadow-sm" id="code" name="code"  value="{!! old('code') !!}">
                                        @include('cms::panel.inc.form_error',['input_name' => 'code'])
                                    </div>
                                    <div class="form-group">
                                        <label>{!! trans('cms::panel.redirects.status') !!}</label>
                                        <div>
                                            <select class="custom-select custom-select-lg form-control shadow-sm" name="status">
                                                <option value="1" >{!! trans('cms::panel.active') !!}</option>
                                                <option value="0" >{!! trans('cms::panel.passive') !!}</option>
                                            </select>
                                        </div>
                                        @include('cms::panel.inc.form_error',['input_name' => 'status'])
                                    </div>
                                    <hr>
                                    <button type="submit" class="btn btn-success" id="submit" value="">
                                        {!! trans('cms::panel.redirects.save') !!}
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

src/Resources/views/panel/redirect/edit.blade.php
@extends('cms::panel.newinc.app')
@push('css')

@endpush

@push('js')
@endpush

@section('content')
    <div class="main-content container-fluid">
        <div class="card">
            <div class="card-header">
                <div class="card-content">
                    <div class="card-body">
                        <div class="divider">
                            <div class="divider-text">{{ trans('cms::panel.redirects.edit') }}</div>
                        </div>
                        <div class="card-content">
                            <div class="card-body">
                                <form method="POST" action="{!! route('redirects.update',['redirect' => $redirect]) !!}" class="form-control-lg">
                                    @method('PUT')
                                    @csrf
                                    <div class="form-group">
                                        <label>{!! trans('cms::panel.redirects.from') !!}</label>
                                        <input type="text" class="form-control shadow-sm" id="from" name="from"  value="{!! old('from') ?? $redirect->from !!}">
                                        @include('cms::panel.inc.form_error',['input_name' => 'from'])
                                    </div>
                                    <div class="form-group">
                                        <label>{!! trans('cms::panel.redirects.to') !!}</label>
                                        <input type="text" class="form-control shadow-sm" id="to" name="to"  value="{!! old('to') ?? $redirect->to !!}">
                                        @include('cms::panel.inc.form_error',['input_name' => 'to'])
                                    </div>
                                    <div class="form-group">
                                        <label>{!! trans('cms::panel.redirects.code') !!}</label>
                                        <input type="text" class="form-control shadow-sm" id="code" name="code"  value="{!! old('code') ?? $redirect->code !!}">
                                        @include('cms::panel.inc.form_error',['input_name' => 'code'])
                                    </div>
                                    <div class="form-group">
                                        <label>{!! trans('cms::panel.redirects.status') !!}</label>
                                        <div>
                                            <select class="custom-select custom-select-lg form-control shadow-sm" name="status">
                                                <option value="1" @if($redirect->status == 1) selected @endif>{!! trans('cms::panel.active') !!}</option>
                                                <option value="0" @if($redirect->status == 0) selected @endif>{!! trans('cms::panel.passive') !!}</option>
                                            </select>
                                        </div>
                                        @include('cms::panel.inc.form_error',['input_name' => 'status'])
                                    </div>
                                    <button type="submit" class="btn btn-success" id="submit" value="">
                                        {!! trans('cms::panel.redirects.save') !!}
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

src/Resources/views/panel/redirect/index.blade.php
@extends('cms::panel.newinc.app')
@push('css')

@endpush

@push('js')
<script>

    $(document).ready( function () {
        $('#myTable').DataTable();
    } );
    </script>
@endpush
@section('content')

    <div class="main-content container-fluid">
        <div class="card">
            <div class="card-header">
                <div class="card-content">
                    <div class="card-body">
                        <div class="divider">
                            <div class="divider-text">{{ trans('cms::panel.redirects.title') }}</div>
                        </div>
                        <div class="alert alert-secondary">
                            <i data-feather="info"></i>{{ trans('cms::panel.redirects.info') }}
                        </div>
                        <div class="divider">
                            <div class="divider-text">{{ trans('cms::panel.redirects.list') }}</div>

                            <div class="form-group">
                                @can('create',CMS\Models\Redirect::class)
                                    <a class="btn icon icon-left btn-primary float-right" href="{!! route('redirects.create') !!}"><i data-feather="plus-circle" ></i>{!! trans('cms::panel.redirects.create') !!}</a>
                                @endcan
                            </div>
                        </div>
                        <div class="card-content">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class='table table-hover' id="myTable">
                                        <thead >
                                        <tr>
                                            <th>{!! trans('cms::panel.id') !!}</th>
                                            <th>{!! trans('cms::panel.redirects.from') !!}</th>
                                            <th>{!! trans('cms::panel.redirects.to') !!}</th>
                                            <th>{!! trans('cms::panel.redirects.code') !!}</th>
                                            <th>{!! trans('cms::panel.redirects.action') !!}</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($redirects as $redirect)
                                            <tr>
                                                <td>{{ $redirect->id }}</td>
                                                <td>{{ $redirect->from }}</td>
                                                <td>{{ $redirect->to }}</td>
                                                <td>{{ $redirect->code }}</td>
                                                <td>

                                                    <a href="{!! route('redirects.edit' , $redirect) !!}" class="btn btn-warning icon"><i data-feather="edit" ></i> {!! trans('cms::panel.edit') !!}</a>
                                                    @can('delete',CMS\Models\Redirect::class)
                                                        @component('cms::panel.newinc.delete_modal',[ 'model' => $redirect, 'route_group' => 'redirects'])
                                                            {!! trans('cms::panel.redirects.delete_text') !!}
                                                        @endcomponent
                                                    @endcan
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection