src/Routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::prefix('/w-admin')->middleware('auth')->group( function () {
    Route::resource('pages' , 'PageController');
    Route::get('pages/{id}/subpages','PageController@subPages')->name('subpages');
    Route::post('pages/checkurl','PageController@urlControl')->name('pages.checkurl');
    Route::resource('files' , 'FileController');
    Route::post('files/ajax','FileController@ajax')->name('file.ajax');
    Route::resource('languages' , 'LanguageController');
    Route::post('languages/update/extensions' , 'LanguageController@extensions')->name('update.Extensions');
    Route::post('languages/update/default' , 'LanguageController@changeDefault')->name('change.default');
    Route::post('languages/update/list','LanguageController@updateList')->name('updateList');
    Route::get('logs','LogController@index')->name('log-index');

    //Category
    Route::resource('categories','CategoryController');
    Route::post('category/order','CategoryController@order')->name('categories.order');
    Route::post('category/getCategory','CategoryController@getCategory')->name('get-category');
    Route::post('category/updateCategory','CategoryController@customUpdate')->name('update-category');
    Route::post('category/sortCategory','CategoryController@sortCategory')->name('sort-category');

    Route::resource('metas' , 'MetaController');
    Route::resource('redirects' , 'RedirectController');

    //Form-Ebulletin
    Route::resource('forms','FormController');
    Route::resource('forms.messages','MessageController');
    Route::resource('messages','MessageController')->only(['show','store']);
    Route::resource('ebulletins' , 'EbulletinController');

    //Auth
    Route::resource('users' , 'UserController');
    Route::resource('roles' , 'RoleController');

    Route::get('/','HomeController@index')->name('panel');

    Route::get('login',function (){ return view('auth/login');})->name('login');

    Route::get('getFilePage','FileController@getFilePage')->name('files.getFilePage');
    Route::get('getFilePageDetail','FileController@getFilePageDetail')->name('files.getFilePageDetail');

    Route::post('saveFilePage','FileController@saveFilePage')->name('files.saveFilePage');
    Route::post('saveFilePageDetail','FileController@saveFilePageDetail')->name('files.saveFilePageDetail');

    Route::post('uploadFile','FileController@uploadFile')->name('files.uploadFile');

    Route::get('googleAnalytics','AnalyticsController@google')->name('analytics.google');

    Route::resource('slider','SliderController');
    Route::post('slider/add-image','SliderController@addImage')->name('addImage');
    Route::post('slider/delete-image','SliderController@deleteImage')->name('delimage');
    Route::post('slider/get-slider-image','SliderController@getSliderImage')->name('getSliderImage');
    Route::post('slider/edit-image','SliderController@editImage')->name('editImage');
    Route::post('slider/sort-image','SliderController@sortImage')->name('sortImage');
    //Menu
    Route::resource('menu', 'MenuController');
    Route::post('menu/ajax','MenuController@ajax')->name('menuajax');
    Route::post('menu/item//delete','MenuController@destroyMenuItem')->name('delete-item');
    Route::post('menuitem/ajax/','MenuController@storeMenuItem')->name('menuitemajax');
    Route::post('menuitem/edit/ajax/','MenuController@editMenuItem')->name('edit-menuitem-ajax');
    Route::post('menu/item','MenuController@getMenuItem')->name('get-menuitem');

});

Route::get('w-admin/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('w-admin/login/', 'Auth\LoginController@login');
Route::post('w-admin/logout', 'Auth\LoginController@logout')->name('logout');


Route::group(['prefix'=>'ebulletin'],function(){
    Route::get('activate/{token}', 'ActionsController@activate')->name('ebulletin.activate');
    Route::get('cancel/{token}', 'ActionsController@cancel')->name('ebulletin.cancel');
    Route::post('save','ActionsController@save')->name('ebulletin.save');
});


Route::post('form/store','MessageController@store')->name('form');
Route::fallback('UrlController@url');

Route::get('/home', 'HomeController@index')->name('home');
Route::any('/ckfinder/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')
    ->name('ckfinder_connector');

Route::any('/ckfinder/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')
    ->name('ckfinder_browser');

src/Models/Role.php
<?php

namespace CMS\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Role extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'name',
    ];

    public function users(){
        return $this->belongsTo('CMS\User');
    }

    public function permissions(){
        return $this->hasMany('CMS\Permission');
    }

    public function hasModulePermission($module_id,$permission){
        $check = ModulePermission::where('role_id',$this->id)
            ->where('module_id',$module_id)
            ->where('permission',$permission)
            ->first();
        return ($check ? true : false);
    }

    public function hasPagePermission($page_id,$permission){
        $check = PagePermission::where('role_id',$this->id)
            ->where('page_id',$page_id)
            ->where('permission',$permission)
            ->first();
        return ($check ? true : false);
    }
}

src/Resources/views/panel/role/create.blade.php
@extends('cms::panel.newinc.app')
@push('css')

@endpush

@push('js')
@endpush

@section('content')

    <div class="main-content container-fluid">
        <div class="card">
            <div class="card-header">
                <div class="card-content">
                    <div class="card-body">
                        <div class="divider">
                            <div class="divider-text">{{ trans('cms::panel.roles.create') }}</div>
                        </div>
                        <div class="alert alert-secondary">
                            <i data-feather="info"></i>{{ trans('cms::panel.roles.createinfo') }}
                        </div>
                        <div class="card-content">
                            <div class="card-body">
                                <form method="POST" action="{!! route('roles.store') !!}">
                                    @method('POST')

                                    @csrf

                                    <div class="form-group">
                                        <label>{!! trans('cms::panel.roles.name') !!}</label>
                                        <input type="text" class="form-control" id="name" name="name" value="{!! old('name') !!}">
                                        @include('cms::panel.inc.form_error',['input_name' => 'name'])
                                    </div>
                                    <div>
                                        <h2>{!! trans('cms::panel.roles.module_permissions') !!}</h2>
                                        @foreach($modules as $module)
                                            <div class="form-group">
                                                <label><strong>{!! trans('cms::panel.roles.module_'.$module->name) !!}</strong></label>
                                                <div>
                                                    <input type="checkbox" class="form-check-input" id="module[{!! $module->id !!}]_create" name="module[{!! $module->id !!}][]" value="C" {{ is_array(old('module.'.$module->id)) && in_array('C',old('module.'.$module->id)) ? 'checked' : '' }}>
                                                    <label for="module[{!! $module->id !!}]_create">{!! trans('cms::panel.roles.crud_create') !!}</label>
                                                    <input type="checkbox" class="form-check-input" id="module[{!! $module->id !!}]_delete" name="module[{!! $module->id !!}][]" value="D" {{ is_array(old('module.'.$module->id)) && in_array('D',old('module.'.$module->id)) ? 'checked' : '' }}>
                                                    <label for="module[{!! $module->id !!}]_delete">{!! trans('cms::panel.roles.crud_delete') !!}</label>
                                                </div>
                                            </div>
                                            @endforeach
                                    </div>
                                    <hr>
                                    <div>
                                        <h2>{!! trans('cms::panel.roles.page_permissions') !!}</h2>
                                        @foreach($pages as $page)
                                            <div class="form-group">
                                                <label>{!! $page->name !!}</label>
                                                <div>
                                                    <input type="checkbox" class="form-check-input" id="page[{!! $page->id !!}]_create" name="page[{!! $page->id !!}][]" value="C">
                                                    <label for="page[{!! $page->id !!}]_create">{!! trans('cms::panel.roles.crud_create') !!}</label>
                                                    <input type="checkbox" class="form-check-input" id="page[{!! $page->id !!}]_delete" name="page[{!! $page->id !!}][]" value="D">
                                                    <label for="page[{!! $page->id !!}]_delete">{!! trans('cms::panel.roles.crud_delete') !!}</label>
                                                </div>
                                            </div>
                                        @endforeach
                                    </div>
                                    <button type="submit" class="btn btn-success" id="submit" value="">
                                        {!! trans('cms::panel.roles.save') !!}
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

src/Resources/views/panel/role/edit.blade.php
@extends('cms::panel.newinc.app')
@push('css')

@endpush

@push('js')
@endpush

@section('content')

    <div class="main-content container-fluid">
        <div class="card">
            <div class="card-header">
                <div class="card-content">
                    <div class="card-body">
                        <div class="divider">
                            <div class="divider-text">{{ trans('cms::panel.roles.edit') }}</div>
                        </div>
                        <div class="alert alert-secondary">
                            <i data-feather="info"></i>{{ trans('cms::panel.roles.editinfo') }}
                        </div>
                        <div class="card-content">
                            <div class="card-body">
                                <form method="POST" action="{!! route('roles.update',array('role'=>$role)) !!}">
                                    @method('PUT')

                                    @csrf

                                    <div class="form-group">
                                        <label>{!! trans('cms::panel.roles.name') !!}</label>
                                        <input type="text" class="form-control" id="name" name="name" value="{!! $role->name !!}">
                                        @include('cms::panel.inc.form_error',['input_name' => 'name'])
                                    </div>
                                    <div>
                                        <h2>{!! trans('cms::panel.roles.module_permissions') !!}</h2>
                                        @foreach($modules as $module)

                                            <div class="form-group">
                                                <label><strong>{!! trans('cms::panel.roles.module_'.$module->name) !!}</strong></label>
                                                <div>
                                                    <input type="checkbox" class="form-check-input" id="module[{!! $module->id !!}]_create" name="module[{!! $module->id !!}][]" value="C" {{ $role->hasModulePermission($module->id,'C') ? 'checked' : '' }}>
                                                    <label for="module[{!! $module->id !!}]_create">{!! trans('cms::panel.roles.crud_create') !!}</label>
                                                    <input type="checkbox" class="form-check-input" id="module[{!! $module->id !!}]_delete" name="module[{!! $module->id !!}][]" value="D" {{ $role->hasModulePermission($module->id,'D') ? 'checked' : '' }}>
                                                    <label for="module[{!! $module->id !!}]_delete">{!! trans('cms::panel.roles.crud_delete') !!}</label>
                                                </div>
                                            </div>
                                        @endforeach
                                    </div>
                                    <hr>
                                    <div>
                                        <h2>{!! trans('cms::panel.roles.page_permissions') !!}</h2>
                                        @foreach($pages as $page)
                                            <div class="form-group">
                                                <label>{!! $page->name !!}</label>
                                                <div>
                                                    <input type="checkbox" class="form-check-input" id="page[{!! $page->id !!}]_create" name="page[{!! $page->id !!}][]" value="C" {{ $role->hasPagePermission($page->id,'C') ? 'checked' : '' }}>
                                                    <label for="page[{!! $page->id !!}]_create">{!! trans('cms::panel.roles.crud_create') !!}</label>
                                                    <input type="checkbox" class="form-check-input" id="page[{!! $page->id !!}]_delete" name="page[{!! $page->id !!}][]" value="D" {{ $role->hasPagePermission($page->id,'D') ? 'checked' : '' }}>
                                                    <label for="page[{!! $page->id !!}]_delete">{!! trans('cms::panel.roles.crud_delete') !!}</label>
                                                </div>
                                            </div>
                                        @endforeach
                                    </div>
                                    <button type="submit" class="btn btn-success" id="submit" value="">
                                        {!! trans('cms::panel.roles.save') !!}
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

src/Resources/views/panel/role/index.blade.php
@extends('cms::panel.newinc.app')
@push('css')

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
@endpush

@push('js')
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script>

    $(document).ready( function () {
        $('#myTable').DataTable();
    } );
    </script>
@endpush

@section('content')

    <div class="main-content container-fluid">
        <div class="card">
            <div class="card-header">
                <div class="card-content">
                    <div class="card-body">
                        <div class="divider">
                            <div class="divider-text">{{ trans('cms::panel.roles.title') }}</div>
                        </div>
                        <div class="alert alert-secondary">
                            <i data-feather="info"></i>{{ trans('cms::panel.roles.info') }}
                        </div>
                        <div class="divider">
                            <div class="divider-text">{{ trans('cms::panel.roles.list') }}</div>

                            <div class="form-group">
                                <a class="btn icon icon-left btn-primary float-right" href="{!! route('roles.create') !!}"><i data-feather="plus-circle" ></i>{!! trans('cms::panel.roles.create') !!}</a>
                            </div>
                        </div>
                        <div class="card-content">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class='table table-hover' id="myTable">
                                        <thead >
                                        <tr>
                                            <th>{!! trans('cms::panel.roles.id') !!}</th>
                                            <th>{!! trans('cms::panel.roles.name') !!}</th>
                                            <th>{!! trans('cms::panel.users.action') !!}</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($roles as $role)
                                            <tr>
                                                <td>{!! $role->id !!}</td>
                                                <td>{!! $role->name !!}</td>
                                                <td>
                                                    <a href="{!! route('roles.edit' , $role) !!}" class="btn btn-warning icon"><i data-feather="edit"></i> {!! trans('cms::panel.edit') !!}</a>
                                                    @component('cms::panel.newinc.delete_modal',[ 'model' => $role, 'route_group' => 'roles'])
                                                        {!! trans('cms::panel.roles.delete_text') !!}
                                                    @endcomponent
{{--                                                    @include('cms::panel.inc.delete_modal',['trans_file' => 'role', 'model' => $role, 'route_group' => 'roles', 'route_parameter' => 'role'])--}}
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection